# This file contains the configuration settings for your Redwood app.
# This file is also what makes your Redwood app a Redwood app.
# If you remove it and try to run `yarn rw dev`, you'll get an error.
#
# For the full list of options, see the "App Configuration: redwood.toml" doc:
# https://redwoodjs.com/docs/app-configuration-redwood-toml

[web]
  title = "SF Carpool"
  port = 8910
#  apiUrl = "/.redwood/functions" # you can customise graphql and dbauth urls individually too: see https://redwoodjs.com/docs/app-configuration-redwood-toml#api-paths

  # NOTE: defaulting to prod URL here since I cant get env vars to evaluate in fly deploy.
#  apiUrl = "http://localhost:8080/v1"
  apiUrl = "${API_URL:https://dmghclecxsldchpsduky.hasura.us-east-1.nhost.run/v1}"
#  apiUrl = "${RWJS_API_URL:testtest8888}"
#  apiUrl = "https://dmghclecxsldchpsduky.hasura.us-east-1.nhost.run/v1"

#  apiGraphqlEndpoint = "http://localhost:8080/v1"
  includeEnvironmentVariables = ['API_URL'] # any ENV vars that should be available to the web side, see https://redwoodjs.com/docs/environment-variables#web
[api]
  enabled = false
#  port = 8911
[browser]
  open = false
