# this file is for local development, not deployment

# version: "3.6"

# version: "3.3"
# name: "electric_local"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
      PG_PROXY_PORT: 65432
      PG_PROXY_PASSWORD: password
    ports:
      - "5133:3000" # HTTP API. 3000 is used by tanstack.
      - "65432:65432" # Postgres proxy for migrations/generate. but process is not starting
    depends_on:
      - postgres
