# this file is for local development, not deployment

# name: "electric_local"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - "5133:3000" # HTTP API. 3000 is used by tanstack.
    depends_on:
      - postgres

  postgrest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: "postgres://postgres:password@postgres:5432/electric?sslmode=disable"
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:4000
      PGRST_DB_ANON_ROLE: postgres
      PGRST_DB_POOL: 10
    ports:
      - 4000:3000
    depends_on:
      - postgres

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:4000/
    depends_on:
      - postgrest
